server:
  port: 8080

spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  #  jpa:
  #    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  h2:
    console.enabled: true
